doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_mapping: false
        mappings:
            Pam:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Pam/Authentication/Entity'
                prefix: 'App\Pam\Authentication\Entity'
            Fixtures:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Fixtures/Entity'
                prefix: 'App\Shared\Fixtures\Entity'
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'
